# travis-ci.org continuous integration testing.

dist: xenial

language: php
php:
  - 7.2

addons:
  mariadb: '10.2'

cache:
  apt: true
  directories:
    # core
    - core-test-framework


env:
  global:
    - WP_TESTS_DIR=core-test-framework
    # ^ needs to be absolute? if so, how to tell what pwd is?

before_install:
  # Download Core unit tests
  - travis_retry svn export https://develop.svn.wordpress.org/trunk/tests/phpunit/ core-test-framework

  # need a Core install too - latest stable

  # Setup database
  mysql -u root -e "CREATE DATABASE wordpress_tests;"
  cp wp-tests-config-sample.php wp-tests-config.php
  sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
  sed -i "s/yourusernamehere/root/" wp-tests-config.php
  sed -i "s/yourpasswordhere//" wp-tests-config.php

before_script:
  # Remove Xdebug for a huge performance increase:
  - phpenv config-rm xdebug.ini

  # Setup code sniffer to run WordPress Code Standard tests
  - composer create-project wp-coding-standards/wpcs --no-dev

  # Install WordPress Coding Standards.
  - mkdir wordpress-coding-standards && curl -L https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/archive/master.tar.gz | tar xz --strip-components=1 -C wordpress-coding-standards

  # Set installed paths for phpcs
  # @link https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-installed-standard-paths
  - wpcs/vendor/bin/phpcs --config-set installed_paths wordpress-coding-standards

  # Create a empty file, which will be passed to phpcs along with all the changed files. This will make sure that incase no php file changes are there, phpcs will not assume that it has to scan whole directory.
  - touch $TRAVIS_BUILD_DIR/tmp.php

  # install phpunit 6.3
  - travis_retry composer global require "phpunit/phpunit:^6"



#  - mysql --version
#  - which phpunit
#  - phpunit --version




script:

  # Run Code Standard Test. This automatically picks up configuration from  phpcs.xml.dist.

  # Exporting list of changed files in CHANGED_FILES variable
  # diff: Get the changed files
  #   --name-only: Get only name of changed files
  #   --diff-filter=AM: Get only (A)dded or (M)odified files. We do not care about deleted files for coding standard test.
  #   $TRAVIS_BRANCH: Base branch we want to merge. Usually this will be master
  #   $TRAVIS_BRANCH...HEAD: List of commits not present in $TRAVIS_BRANCH, but present in HEAD
  # tr '\n' ' ': Convert from list of filenames seperated by `\n` to list of filenames seperated by ' '
  - export CHANGED_FILES=$(git diff --name-only --diff-filter=AM $TRAVIS_BRANCH...HEAD | tr '\n' ' ')

  # `wpcs` is where we have installed the code sniffer
  # -v flag: Print verbose output
  # -n flag: Do not print warnings
  # -p flag: Show progress of the run
  # --extensions=php: Only sniff php files
  # tmp.php: So that phpcs do not assume that it has to scan all files in case no php files are changed.
  - wpcs/vendor/bin/phpcs -v -n -p --extensions=php $TRAVIS_BUILD_DIR/tmp.php $(echo $CHANGED_FILES)

# Run unit test suite
  - phpunit